### ISSUE TITLE
Strings with different starting and ending quote should be treated as invalid

### ISSUE THREAD

**Issue by jarek-foksa** [tabatkins/parse-css#40]
Calling ```tokenize(`"a'`)``` should return `BAD_STRING` rather than `STRING` token, at least this is how I understand [the grammar](https://drafts.csswg.org/css-syntax-3/#string-token-diagram).

**Comment by tabatkins** [comment]
Nope, remember that those grammar railroads describe what a valid token looks like while ignoring error-handling, etc.  In particular, EOF auto-closes all open constructs (including strings) - check [the "parse a string" section](https://drafts.csswg.org/css-syntax-3/#consume-string-token). Hitting EOF with an open string is a parse error, but it still returns an ordinary string token.

(That token happens to contain `a'` in your example; the single-quote is part of the string's value, not something that closes the string.)
