### ISSUE TITLE
parser or example.html issues with nesting at-rules

### ISSUE THREAD

**Issue by jonathantneal** [tabatkins/parse-css#44]
The parser token and JSON results appear different to me when parsing nesting at-rules. I’m unsure if the parser itself has issues parsing nesting at-rules, or if this is a limitation within the example.html demo.

Here is the CSS that I parsed:

```pcss
@media screen {
	body {
		background-color: blue;
	}
}

@media all {
	@media screen {
		body {
			background-color: blue;
		}
	}
}
```

The tokens output looks correct, labeling 2 root at-rules and 1 nesting at-rule:

```dingus
AT(media) WS IDENT(screen) WS {
	WS IDENT(body) WS {
		WS IDENT(background-color) : WS IDENT(blue) ;
	WS }
WS }

WS AT(media) WS IDENT(all) WS {
	WS AT(media) WS IDENT(screen) WS {
		WS IDENT(body) WS {
			WS IDENT(background-color) : WS IDENT(blue) ;
		WS }
	WS }
WS }
```

The JSON output looks incorrect, identifying the final nesting at-rule as a keyword in the value of the 2nd root at-rule:

```json
{
	"type": "STYLESHEET",
	"value": [
		{
			"type": "AT-RULE",
			"name": "media",
			"prelude": [
				{
					"token": "WHITESPACE"
				},
				{
					"token": "IDENT",
					"value": "screen"
				},
				{
					"token": "WHITESPACE"
				}
			],
			"value": {
				"type": "BLOCK",
				"name": "{",
				"value": [
					{
						"token": "WHITESPACE"
					},
					{
						"token": "IDENT",
						"value": "body"
					},
					{
						"token": "WHITESPACE"
					},
					{
						"type": "BLOCK",
						"name": "{",
						"value": [
							{
								"token": "WHITESPACE"
							},
							{
								"token": "IDENT",
								"value": "background-color"
							},
							{
								"token": ":"
							},
							{
								"token": "WHITESPACE"
							},
							{
								"token": "IDENT",
								"value": "blue"
							},
							{
								"token": ";"
							},
							{
								"token": "WHITESPACE"
							}
						]
					},
					{
						"token": "WHITESPACE"
					}
				]
			}
		},
		{
			"type": "AT-RULE",
			"name": "media",
			"prelude": [
				{
					"token": "WHITESPACE"
				},
				{
					"token": "IDENT",
					"value": "all"
				},
				{
					"token": "WHITESPACE"
				}
			],
			"value": {
				"type": "BLOCK",
				"name": "{",
				"value": [
					{
						"token": "WHITESPACE"
					},
					{
						"token": "AT-KEYWORD",
						"value": "media"
					},
					{
						"token": "WHITESPACE"
					},
					{
						"token": "IDENT",
						"value": "screen"
					},
					{
						"token": "WHITESPACE"
					},
					{
						"type": "BLOCK",
						"name": "{",
						"value": [
							{
								"token": "WHITESPACE"
							},
							{
								"token": "IDENT",
								"value": "body"
							},
							{
								"token": "WHITESPACE"
							},
							{
								"type": "BLOCK",
								"name": "{",
								"value": [
									{
										"token": "WHITESPACE"
									},
									{
										"token": "IDENT",
										"value": "background-color"
									},
									{
										"token": ":"
									},
									{
										"token": "WHITESPACE"
									},
									{
										"token": "IDENT",
										"value": "blue"
									},
									{
										"token": ";"
									},
									{
										"token": "WHITESPACE"
									}
								]
							},
							{
								"token": "WHITESPACE"
							}
						]
					},
					{
						"token": "WHITESPACE"
					}
				]
			}
		}
	]
}
```

**Comment by tabatkins** [comment]
That's correct, actually - CSS's grammar is ambiguous, and can't tell a priori whether the contents of a block should be interpreted as properties&at-rules or style-rules&at-rules. So the parser just keeps everything as a component-value stream instead, which you can then call the correct parser function on.

Note the canonicalize() function starting at <https://github.com/tabatkins/parse-css/blob/master/parse-css.js#L1291>, which will do this automatically for well-known CSS rules, according to the CSSGrammar at <https://github.com/tabatkins/parse-css/blob/master/parse-css.js#L1291>

**Comment by tomhodgins** [comment]
@jonathantneal I've made a little demo page here that lets you enter text for any of the Parser Entry Points and then check the console for the full AST when parsed as that thing: https://tomhodgins.com/demo/css/

I guess when we're using it for custom stuff we'll have to figure out how to define our own grammar and find a way to validate that, so a `@--custom {}` at-rule would know to parse a list of rules inside, but `@--demo something;` wouldn't try to look for rules.

…Still figuring that part out :3

**Comment by tabatkins** [comment]
at-statement vs at-block isn't a problem; that's unambiguous in the syntax based on whether you have a `;` or a `{` at the end of the prelude.

I'll again point at the canonicalize() function already present in the repo, which gives a way to express whether an at-rule contains qualified rules (like @media or @keyframes) or declarations (like @font-face or @counter-style), and does the parsing for you to give you a good list of either rules or declarations. ^_^
