### ISSUE TITLE
`escapeIdentCode` doesn't exist.

### ISSUE THREAD

**Issue by romainmenke** [tabatkins/parse-css#46]
https://github.com/tabatkins/parse-css/blob/998aced565ad5d658196b557e255effaa7d4abe8/parse-css.js#L801

```
ReferenceError: escapeIdentCode is not defined
```

**Comment by tabatkins** [comment]
Whoops, clearly I meant to extract that and didn't. Fixed, thanks.

**Comment by romainmenke** [comment]
Works great 🎉
