### ISSUE TITLE
`HashToken.type` is incorrect when it is an `id`

### ISSUE THREAD

**Issue by romainmenke** [tabatkins/parse-css#47]
https://github.com/tabatkins/parse-css/blob/df2089c6e2f067e0edef88e27906d333baffdab9/parse-css.js#L155

This clashes with the `type` that all tokens have and that distinguishes them.

Other `HashToken` instances have `instance.type === 'HASH'` but when it is an id, it is set to `id`.

-----

Before the recent refactor `HASH` was stored in `tokenType` and it didn't clash.

**Comment by tabatkins** [comment]
Argh I fixed NumberToken when I moved everything consistently to .type, but forgot about HashToken.

**Comment by tabatkins** [comment]
Okay fixed, and also updated numbers to match the new simplified spec and properly set and use the sign value.

**Comment by romainmenke** [comment]
Thank you 🙇
