### ISSUE TITLE
Parsing nested rules is considerably slower than parsing top-level rules

### ISSUE THREAD

**Issue by soitchu** [tabatkins/parse-css#60]
I'd like to preface this by saying that I am quite new to CSS parsing, so I could be overlooking something very obvious; apologies if that's the case. And I am not sure if this is the right place to ask this either.

It seems like when parsing nested rules, the complexity is O(n<sup>2</sup>) because `consumeTheRemnantsOfABadDeclaration` is called for every subsequent rule. For example:

```css
.z {
  .a {
    color: red;
  }

  .b {
    color: blue;
  }

  .c {
    color: green;
  }
  
  .d {
    color: green;
  }
}
```
Here's what parsing this CSS looks like:

- Tries to parse `.a` as a declaration
- Since it isn't a declaration,  `consumeTheRemnantsOfABadDeclaration` is called
- `consumeTheRemnantsOfABadDeclaration` then loops until it hits the end of the parent rule, i.e. the end of the file in the above example.
- The input then reverts back to `.a` and parses it as a rule.

Essentially, when parsing `.a`, it goes through `.b`, `.c`, `.d`, and when parsing `.b` it goes through `.c` and `.d`. This turns the complexity of parsing nested rules to O(n<sup>2</sup>). 

I did double check `https://drafts.csswg.org/css-syntax/` to see if this was an implementation issue, and it seems like it's not. And for what it's worth, we also have a custom implementation based off the CSS Syntax spec, and it runs into the same issue. I know that we could follow `Consume a block’s contents`'s implementation notes to optimize this, but I wanted to make check whether this behavior is indented or not.

**Comment by tabatkins** [comment]
Yes, it's intended behavior, but the optimization notes are *also* intended for implementations to use (I haven't adopted them into this library yet).

**Comment by soitchu** [comment]
That makes sense. Thank you!
